[package]
name = "picoswap-ergo-headless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ergo-headless-dapp-framework      = "0.1.0"
ergo-lib                          = "0.15.0"